### ISSUE TITLE
Video streaking/distortions on real hardware

### ISSUE THREAD

**Issue by meeq** [DragonMinded/libdragon#159]
I noticed this on my [Flappy Bird](https://github.com/meeq/FlappyBird-N64) project -- it looks fine on emulators, but on real hardware the video signal has big smears and streaks.

Flappy Bird uses the following arguments to `display_init`: 

```
RESOLUTION_320x240, DEPTH_16_BPP,
BUFFERING_DOUBLE, GAMMA_NONE, ANTIALIAS_RESAMPLE
```

Terrible photo attached:
![image](https://user-images.githubusercontent.com/11916110/127412457-f61f3b29-a356-4ddf-9147-0ecc554815c4.jpeg)

Terrible video link:
https://media.discordapp.net/attachments/627380625766088715/861113817676513301/VID_20210704_001720.mp4

fpgashibe on N64brew Discord seemed to think it was because the VI was not being set up correctly by the Display subsystem: https://discord.com/channels/205520502922543113/627380625766088715/861758855331840032

Marshall was also able to reproduce zebra striping artifacts by launching the LibDragon `ctest` example ROM after a reset from Animal Forest: https://discord.com/channels/205520502922543113/763114214688555039/870091995132071966

**Comment by parasyte** [comment]
This is caused by the "dither filter" bit set in 16-bit mode: https://github.com/DragonMinded/libdragon/blob/fd45d487f48885883e341a8facd9e8276fa410cf/src/display.c#L322-L326

Changing the value to `0x2` fixes the vertical bars.

And if you enable antialiasing, the vertical bars will not be present with dither filter also enabled. Unfortunately, the antialias filtering is pretty bad.

**Comment by werkn** [comment]
@parasyte I'm also getting the vertical bars like @meeq mentions in my apps, are we just setting `control |= 0x20002` or `control |= 0x2`?  Thanks for any help (I'm using the exact same setup for `display_init`, so `RESOLUTION_320x240, DEPTH_16_BPP,
BUFFERING_DOUBLE, GAMMA_NONE, ANTIALIAS_RESAMPLE`)

**Comment by parasyte** [comment]
@werkn The latter. This will fix the vertical bars, if you are _not_ using antialiasing:

```c
control |= 0x2;
```

Alternatively, especially if you do not want to patch `libdragon`, you can just enable antialiasing by passing `ANTIALIAS_RESAMPLE_FETCH_ALWAYS` to `display_init()`. Bear in mind the quality caveat mentioned earlier.

**Comment by werkn** [comment]
@parasyte Can confirm applying `ANTIALIAS_RESAMPLE_FETCH_ALWAYS` fixes this issue, screenshot attached with my call to `display_init(..)`.

![image](https://user-images.githubusercontent.com/10902433/131200020-436bfe07-d493-42b3-ad69-e553a611f1bb.png)

Thanks for the help :+1:

**Comment by meeq** [comment]
Closing this; I can confirm that `ANTIALIAS_RESAMPLE_FETCH_ALWAYS` fixes the issue in FlappyBird. Thanks!

**Comment by rasky** [comment]
Is there something we can do in libdragon to avoid people having the problem in the first place? cc @sp1187

**Comment by rasky** [comment]
FWIW, this has been generally fixed in https://github.com/DragonMinded/libdragon/commit/8676c7b284dd051ffd1b8c1ca4e25adef0bf9e2b so that others won't hit the same issue.

**Comment by rasky** [comment]
To followup on this, the above patch had a bug: in fact, dither filter only works without artifacts in the `ANTIALIAS_RESAMPLE_FETCH_ALWAYS` mode (that is, when the `AA_MODE` bits are `00`). The patch above enabled it also for `ANTIALIAS_RESAMPLE_FETCH_NEEDED` (`AA_MODE = 01`).

This has then been fixed by https://github.com/DragonMinded/libdragon/commit/8ded366e155b98fb631c57a22257494fe7507d15 which reworked the API in addition to fixing the bug.
