### ISSUE TITLE
Link tests are not allowed after GCC_NO_EXECUTABLES

### ISSUE THREAD

**Issue by adrigen** [DragonMinded/libdragon#22]
I run into this issue when trying to build the toolchain on mint linux.
I appologise if this stems from my lack of experience with linux, gcc and building from source in general, but I was wondering if I might be from following the readme to rigidly? Can you suggest a better forum for getting assistance with building the toolchain?
http://pastie.org/10242162

**Comment by rveens** [comment]
ive got the same problem

**Comment by AndrewKralovec** [comment]
You guys are Window users, correct?

**Comment by rveens** [comment]
Nope. Ubuntu 14.04. i pulled your code and tried to compile it, i changed nothing.

**Comment by adrigen** [comment]
Ditto.

aus: 0435828690

skype, del.icio.us, facebook: adrigen

http://seedy.adrian.com.au/ - Receive monthly seed packets with a selection
of vegetables which are in season for planting.

**Comment by urbistm** [comment]
Hi there! I don't know if you got to solve this problem, but I encountered this same issue yesterday while compiling the toolchain. Today I have finally be able to compile all of it.

To solve the GCC_NO_EXECUTABLES issue for the configure-zlib line, I first have installed the library "zlib1g-dev" directly into my Ubuntu distro, and then I have modified the build script to include the flag "--with-system-zlib" in the two steps that compile gcc, just after the flag "--with-newlib".

After two hours compiling, it all ended well. Now I'm struggling with libdragon itself, it gives me an error making the tools, mksprite more exactly, due to some problem with the libpng library I have installed...

**Comment by Dekken** [comment]
Just had this issue on CentOS6.7. Cheers urbistm, your suggestion worked.

**Comment by ArtemioUrbina** [comment]
You can fix the mksprite issue bu changing the Makefile to:

INSTALLDIR = $(N64_INST)
CFLAGS = -std=gnu99 -O2 -Wall -Werror -I../../include
LDLIBS = -lpng

all: mksprite convtool

mksprite: mksprite.c
convtool: convtool.c

install: mksprite convtool
	install -m 0755 mksprite $(INSTALLDIR)/bin
	install -m 0755 convtool $(INSTALLDIR)/bin

.PHONY: clean install

clean:
	rm -rf mksprite
	rm -rf convtool

**Comment by anacierdem** [comment]
This will be fixed if #37 is merged.
