### ISSUE TITLE
docker-build fails on forks

### ISSUE THREAD

**Issue by networkfusion** [DragonMinded/libdragon#220]
When running the CI on forks, the docker-build.yml expects that it will be able to push to the "dragonminded" container repo. That is not the case, so the build fails.

A condition should be set so this does not happen and/or an easy way to specify the path (through a variable) for the users own docker registry path.

**Comment by networkfusion** [comment]
@anacierdem tagging you into this as most likely to fix.

**Comment by anacierdem** [comment]
That was something I needed to break the last minute (just after we merged the workflows). It should work for branches though. It was an oversight of me using the committer's username instead of the repo owner and I had to hardcode it then. Also upper case letters in DragonMinded was a problem that needs attention. I will look into this sometime.

**Comment by networkfusion** [comment]
This build can be checked for reasons... https://github.com/networkfusion/libdragon/runs/4070473399?check_suite_focus=true

**Comment by anacierdem** [comment]
From what I see I have fixed the login to repo owner, the only issue is the lowercase conversion IINM

**Comment by networkfusion** [comment]
Seems to have been a local build issue.
