### ISSUE TITLE
Configure access to packages

### ISSUE THREAD

**Issue by rasky** [DragonMinded/libdragon#230]
@DragonMinded can you please follow this guide to configure access to packages so that it inherits the repository permissions?
https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#inheriting-access-for-a-container-image-from-a-repository

Basically, I think it would be useful now and for the future if the same people that have commit access can also push to the package registry. I think this is the reason why #228 is failing right now with authentication error.

**Comment by DragonMinded** [comment]
It already is configured that way.

**Comment by rasky** [comment]
@DragonMinded can you try this instead:
https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio

**Comment by DragonMinded** [comment]
It was already there, so I deleted it and re-added it with write permissions again.

**Comment by anacierdem** [comment]
A few notes here to clarify things and for future reference:
For non-organization accounts the *Inherited Access* and *Manage Actions access* settings are found under package;
![image](https://user-images.githubusercontent.com/6522751/160072013-7075ea43-acb1-462f-916c-7b8973c2c561.png)

I am trying a few different options so that we may understand the situation better.

- Login with `${{ github.actor }}` and `${{ secrets.GITHUB_TOKEN }}` and pushing the changes to a branch on the upstream [repository](https://github.com/DragonMinded/libdragon/actions/runs/2038477287) & a branch on [a fork](https://github.com/anacierdem/libdragon/actions/runs/2038478136). Both pushes fail.
- Login with `${{ github.repository_owner }}` and `${{ secrets.GITHUB_TOKEN }}` and pushing the changes to a branch on the upstream [repository](https://github.com/DragonMinded/libdragon/actions/runs/2038531559) & a branch on [a fork](https://github.com/anacierdem/libdragon/actions/runs/2038531369). Both pushes fail.

This looks like there is an issue such that the `GITHUB_TOKEN` on our pushes does not have write access to `ghcr.io/dragonminded/libdragon` for some reason. Interestingly, I remember that `docker-build.yml` triggered from a push to `trunk` was working with with `${{ github.repository_owner }}` and `${{ secrets.GITHUB_TOKEN }}` even if the push is initiated by the collaborators (from back when I first implemented this - so I haven't verified it recently). Also PR merges are still able push with a similar configuration even though they are started from a collaborator context.

- Login with `${{ github.actor }}` and `${{ secrets.GITHUB_TOKEN }}` and pushing the changes to a branch on the upstream [repository](https://github.com/DragonMinded/libdragon/runs/5688098035?check_suite_focus=true) & a branch on [a fork](https://github.com/anacierdem/libdragon/actions/runs/2038584473) with the ghcr.io package set to publish it on the fork's repository. Boh of these failsmeaning that the push context on the upstream and forked repository cannot access a package on the fork even though I am the one initiating the workflow.

At this point I'm pretty convinced that there is something wrong with the action. I will investigate further.

**Comment by anacierdem** [comment]
I think I have found the issue, `docker/build-push-action` expects the `ghcr.io` prefix but `docker/metadata-action` does not include it. Thus the build action tries to push to the default registry (probably docker hub) I will verify and fix the related PR.

**Comment by anacierdem** [comment]
The fix failed with a `403` this [time](https://github.com/DragonMinded/libdragon/actions/runs/2038979194). I will try to investigate further.

**Comment by anacierdem** [comment]
With the latest fixes, I managed to make it work on forked repositories using `github.actor` as the username on repositories whose owners are collaborators of the upstream repo (via inherited access).
For pull request runs, the token only grants read access. This seems something inheritent to PR runs: https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
> Pull requests from public forks are still considered a special case and will receive a read token regardless of these settings.

So we are unable to push images for PR runs.

I believe the collaborators should be able to push images from pushes to their own forks, but the same would be possible by just pushing to a branch in the upstream repository. So this is possibly a dead end for now. I'm closing this issue as there isn't an available permission to enable this.

**Comment by anacierdem** [comment]
I have also tried pushing from my fork but I was unable to push the image from there as well. There might still be a permission issue but it still does not help with the original purpose. Also note that a PR opened from the main repository have write access, which resulted in very confusing cases in my tests.

**Comment by rasky** [comment]
OK so if I understand correctly, the feature of pushing docker images for PRs only work if the PR is opened from a branch of the same repo. That is, if we want to test a change to the toolchain, we could push a branch in libdragon's upstream and open a PR from there -- it would work.

I think this is fine, now that we know it. Better than nothing. Only thing: do you think there's a way to change the GitHub action so that it only tries to push the docker file *if* the PR is opened from the same repo? This would avoid build failures for toolchain changes in PRs from forks (simply, the Docker file wouldn't be available in that case).

**Comment by anacierdem** [comment]
> I have also tried pushing from my fork

I mean, I tried pushing from my fork to the upstream repo.

Actually it also works just fine even if it is not the same repo. i.e it will push to the fork's package repository instead and build will not fail. I have changed the PR to behave like this and I'm testing it with the full build to make sure now.

> the Docker file wouldn't be available in that case

Why wouldn't it be available?
