### ISSUE TITLE
Any way to increase frame drawing times?

### ISSUE THREAD

**Issue by Acceptable67** [DragonMinded/libdragon#235]
I absolutely adore developing with LibDragon, but the majority of my ROMs face either a flickering issue (RDP is too quick and software can't keep up with drawing) or slow ability to render. 
For instance to draw pixels 256x240 every frame buffer, it comes out to about 0.3 seconds and, even with trivial geometric shapes and calculations, I'm still suffering from slowdown in the range of 0.15-0.3 seconds per frame. 

I've been trying forever to figure out what is the best way to go about this. Mind you, this is with RDP clearing the screen as to have maximum performance. I've drawn directly to the frame buffer with the same results.

My ROMs built with the Nintendo SDK seem to function fine in regards to the frame rate. What do you guys think could be the bottleneck here?

**Comment by rasky** [comment]
Can you share a sample that shows the behavior you see? That might make it easier to debug

**Comment by Acceptable67** [comment]
thanks for the quick reply!
I've made a really quick video. https://www.youtube.com/watch?v=41s1DMCNOL4

these are a couple quick examples of some of the issues I'm facing regarding objects being drawn. I think what I'm looking for is 'double buffering' but I'm not entirely sure how to implement it.

**Edit:** Made great progress on the flickering. [Take a look. ](https://www.youtube.com/watch?v=jutB668M_-o)The placement on where the display is locked, as well as when it is shown is very important. seems if it's too far away from the drawing code you will get lines like I was experiencing. Now all that is left is to figure out why rendering the 256x240 RayCasting ROM is so slow.

The screen is drawn every frame within a nested screenwidth * screenheight loop, with every x increment drawing 240(screenheight()) equivalent pixels. Perhaps this is too much for the VR4300 to handle software-wise?

**Comment by rasky** [comment]
I'm sorry it's a bit hard for me to follow without having access to source code.

In general, you are expected to call `display_lock` to get a handle to it, then draw on it with either CPU or RDP (or both, but make sure they don't step on each other), and when both are finished (including RDP which goes in parallel) you can call `display_show`. If you follow this pattern, your screen will not flicker. If the frame calculation time is too slow, you will get a slow framerate, but no flickering.

**Comment by Acceptable67** [comment]
No problem! good to know about the display, I'm surprised I didn't make the connection earlier. 
My main issue was with the flickering but now that it is squared away I suppose it's more about how can I refractor my code to run for efficiently. If you would like to take a look, my source is [available here: ](https://github.com/Acceptable67/LibN64-CPP-LibDragon-Wrapper/blob/main/LibN64GameTest/LibN64GameTest.cpp)

**Comment by robmccoll** [comment]
I know nothing about N64 development, don't know how well g++ will optimize for this backend, and just stumbled across this out of curiosity, so YMMV, but:

- A lot of calls to things like ScreenHeight() and ScreenWidth() - might want to save this somewhere (or statically define it). It shouldn't change.
- Similarly, I see a floating point divide by 2.0 of that value which is an integer, so it could just be a simple right shift (which is cheap and you could  save it and not recompute).
- You could probably refactor the ceiling - wall - floor loop into a loop to do ceiling, a loop for wall, and a loop for floor.
- Some of your while loops could use break statements rather than checking a bool every iteration.
- Anything you can do to reduce multiplication and division (especially floating point). These instructions stall the ALU pipeline and effectively consume way more CPU cycles.

Remember that you're doing software raycasting, which is actually surprisingly expensive overall. Doing this efficiently on computers of the mid-90s was quite a challenge. If you are curious about what sorts of operations are especially costly on the N64, this is the manual for the processor http://datasheets.chipdb.org/NEC/Vr-Series/Vr43xx/U10504EJ7V0UMJ1.pdf

**Comment by robmccoll** [comment]
Ah, you are also using a more naïve ray-casting approach that doesn't take advantage of your fixed-size grid. This guide https://permadi.com/1996/05/ray-casting-tutorial-7/ has a more efficient algorithm you might want to look into.

**Comment by Acceptable67** [comment]
Thanks Rob! Will take a look
