### ISSUE TITLE
libmikmod issue

### ISSUE THREAD

**Issue by vieux** [DragonMinded/libdragon#32]
Hi, I'm on ubuntu16:04 and I'm having trouble compiling the `dfsdemo`

When I try to download the sources, and complile with `./configure --prefix=${N64_INST} --target=mips64-elf` it tells me `kipping incompatible /usr/mips64-elf/lib/libmikmod.a when searching for -lmikmod`

Any idea ?

**Comment by sp1187** [comment]
Upstream mikmod does not seem to have any N64 support, and the error message is probably because mikmod accidentally gets compiled for the wrong architecture. You will probably have better luck by using https://github.com/networkfusion/libmikmod, compile it by running `make` and `make install` in the `n64` folder. 

You may have to apply this patch to the N64 mikmod Makefile:
```diff
--- a/n64/Makefile
+++ b/n64/Makefile
@@ -1,4 +1,4 @@
-CFLAGS = -std=gnu99 -O2 -G0 -Wall -mtune=vr4300 -march=vr4300 -I$(N64_INST)/include -I$(N64_INST)/mips64-elf/include -I$(CURDIR)/../include/ -I$(CURDIR)/ 
+CFLAGS = -std=gnu99 -O2 -G0 -Wall -mtune=vr4300 -march=vr4300 -I$(N64_INST)/mips64-elf/include -I$(CURDIR)/../include/ -I$(CURDIR)/
 CFLAGS += -DDRV_N64
 
 ASFLAGS = -mtune=vr4300 -march=vr4300
@@ -20,8 +20,8 @@ createdir:
        @mkdir -p $(CURDIR)/build/
 
 install: libmikmod.a $(CURDIR)/../include/mikmod.h
-       install -m 0644 libmikmod.a $(INSTALLDIR)/lib/libmikmod.a
-       install -m 0644 $(CURDIR)/../include/mikmod.h $(INSTALLDIR)/include/mikmod.h
+       install -m 0644 libmikmod.a $(INSTALLDIR)/mips64-elf/lib/libmikmod.a
+       install -m 0644 $(CURDIR)/../include/mikmod.h $(INSTALLDIR)/mips64-elf/include/mikmod.h
 
 .PHONY: clean
 clean:
```

**Comment by vieux** [comment]
@sp1187 thanks! works great
